// components/ResumeExamples.js

import Image from "next/image";

const HomeThirdSec = () => {
  const resumes = [
    {
      id: 1,
      webpSrc:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-1-small.6c8738b9c6d5.webp",
      src: "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-1-small.1934cea92fea.png",
      alt: "Resume sample generated by Kickresume AI resume writer.",
      thumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-1.7d5288904a42.png",
      webpThumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-1.c7476a129407.webp",
    },
    {
      id: 2,
      webpSrc:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-2-small.57c34078cbb0.webp",
      src: "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-2-small.398a16728689.png",
      alt: "Resume sample generated by Kickresume AI resume writer.",
      thumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-2.9dad8585953c.png",
      webpThumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-2.4cfa1fc26ece.webp",
    },
    {
      id: 3,
      webpSrc:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-3-small.aa0436ffad44.webp",
      src: "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-3-small.6cc5202546a9.png",
      alt: "Resume sample generated by Kickresume AI resume writer.",
      thumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-3.a4c8c3be3430.png",
      webpThumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-3.7c094797b365.webp",
    },
    {
      id: 4,
      webpSrc:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-4-small.f4eeedc51d5f.webp",
      src: "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-4-small.0fd44f2f7bed.png",
      alt: "Resume sample generated by Kickresume AI resume writer.",
      thumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-4.150fa2d5abe7.png",
      webpThumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-4.defb36d6b9cb.webp",
    },
    {
      id: 5,
      webpSrc:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-5-small.6264b76f872b.webp",
      src: "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-5-small.3999d64da485.png",
      alt: "Resume sample generated by Kickresume AI resume writer.",
      thumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-5.9e6f2fd29841.png",
      webpThumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-5.524b1c00132e.webp",
    },
    {
      id: 6,
      webpSrc:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-6-small.b4b0dbcca01f.webp",
      src: "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-6-small.4d08cbafa6ea.png",
      alt: "Resume sample generated by Kickresume AI resume writer.",
      thumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-6.6c8818263378.png",
      webpThumbnailUrl:
        "https://d1civoyjepycei.cloudfront.net/static/img/ai_resume_samples/ai-resume-6.63560d1c4ad5.webp",
    },
  ];

  return (
    <>
      <div className="section section--resumes bg-green-50 has-lines bottom-only py-16 px-14">
        <div className="container">
          <div className="section-title text-center mb-12">
            <h2 className="mini-headline text-xl font-semibold">
              AI Generated Resume
            </h2>
            <h2 className="h1 headline text-4xl font-bold">
              AI-Generated Resume Examples
            </h2>
            <p className="text-lg mt-4">
              What does an AI-generated resume look like? See for yourself!
              <br /> These resumes were generated by our AI resume builder.
            </p>
          </div>
          <div className=" all-resumes grid grid-cols-3 gap-6 px-16">
            {resumes.map((resume) => (
              <div
                key={resume.id}
                className="all-resumes__box  bg-white rounded-lg shadow-lg overflow-hidden relative group"
              >
                <picture>
                  <source srcSet={resume.webpSrc} type="image/webp" />
                  <Image
                    width={424}
                    height={600}
                    loading="lazy"
                    className="img-fluid w-full h-auto"
                    src={resume.src}
                    alt={resume.alt}
                  />
                </picture>
                <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                  <button
                    type="button"
                    className="bg-blue-500 text-white py-2 px-4 rounded-lg"
                    data-toggle="modal"
                    data-target="#templatePreviewModal"
                    data-template-btn-display="none"
                    data-template-name={resume.alt}
                    data-template-type="resume"
                    data-thumbnail-url={resume.thumbnailUrl}
                    data-webp-thumbnail-url={resume.webpThumbnailUrl}
                  >
                    Preview
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default HomeThirdSec;
